on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false
      - name: Test
        run: go test ./...
